### PR TITLE
Initial Events

### PR DESCRIPTION
**Pull request by d3x0r**
Implemented on_configuration_changed event and extended event lib to dispatch to entities registered.
Update baseMaxPower in control/train to expected train power.

on first update, onLoad will set basePowerMax to 'nil' momentarily then onConfigChange should fix it and onLoad retrigger.

(untested)

### CODE REVIEW

**Review by Hermios — COMMENTED** [review]
Hi d3xOr
Many Thanks for your changes. I will be more than happy to merge them, but please first comply with my current system :
no global data is required, as you can directly initialize data at the first tick.
Please add a global variable in the block 
"if not init then..." at the end of the file control.lua
I don't pretend that my is better than yours (I am actually convinced that yours is better!), but this is how I developed all my mods, and I would like to keep some consistencies between them (Actually, I may change this one as it is not enough consistent with the others, but... later).
I will look now at your other tips and implement it accordingly
Thanks again for your help

P.S.:Wait, I will update to have a better organized system, then you can add your code (I'll let you add this one, or can do it myself, as you want)

**Comment by d3x0r** [comment]
Sure; my original version was just on-tick; but then that adds an extra do nothing at every tick so it was more optimal to use global data and recover it in the startup.
can't add it at the end of control.lua because maxPowerReqwuired is local to train.lua
:) I'll let you ponder it; just figured I'd throw it out there.

**Comment by d3x0r** [comment]
This other mod I started with; Upgrade Builder and Planner uses a lot of global data.  it's not like there's any tricks to using it; and it's private to the mod anyway so that makes it less tricky.

**Comment by Hermios** [comment]
Yep,
as said, I am pretty sure that your code is better than mine, mine is just complying (sort of!) with my other mods. I changed now my files architecture for this one, to be like others (I am tired to search for information that may be easy to find in other mods). I'l update it once it has been tested, then I will check what you explained on the forum, and update as you suggested

**Comment by Hermios** [comment]
Ok, update has been done, and the good news is, no restriction on names for rails. Just add them in the correct order (straight, then curve names) when you call the remote function.
I added as well the dynamic basePowerMax.
For the rest, I am not entirely convinced : By removeing the /60, I require more electricity, but not sure that it changes anything.
For the drain energy of accu not set to 0... I don't know what kind of test you did, but by me, energy is accumulated and I quickly reach amazing amount of energy. And when the train stops, this energy is still consumed.
But the problem with the multiple loco is still present, I will test your idea and check.
Thanks

Hermios

**Comment by d3x0r** [comment]
I was saying you don't have to set energy_drain at all.  you could leave it 0.  Yes if there is a drain, it will consume energy.
it's requiring more energy without the /60 because it is filling the accumulator AND having a drain (that goes nowhere)

**Pull request closed without merging**
